export const APP_STRINGS = {
  login: {
    title: 'TechErudite',
    subtitle: 'Empowering minds, scaling horizons',
    formTitle: 'Welcome Back',
    formSubtitle: 'Sign in to your tech portal',
    emailLabel: 'Email',
    emailPlaceholder: 'email@email.com',
    passwordLabel: 'Password',
    passwordPlaceholder: 'Password',
    buttonText: 'Sign In',
    forgotPasswordText: 'Forgot Password?',
    footerText: 'Not a member? ',
    signUpText: 'Sign Up Here',
    logo: 'Pliē',
    imagePlaceholder: '🖼',
    orText: 'or Sign In with:',
    guestText: 'Enter as Guest',
  },
  events: {
    greeting: 'Hey Renzo,',
    greetingSubtitle: "Let's explore your events.",
    headerTitle: 'Tech Events',
    headerSubtitle: 'Are you ready to dance?',
    logoutText: 'Log Out',
    searchPlaceholder: 'Search events, workshops...',
    emptyText: 'No events found matching your filter',
    attendingEmoji: '🔥',
    attendingSuffix: 'Attending',
    registerText: 'Register',
  },
  favourites: {
    emptyText: 'No favourites yet',
  },
  profile: {
    title: 'Profile Screen',
    logoutText: 'Log Out',
  },
  tabs: {
    search: 'Search',
    events: 'Events',
    favourites: 'Favourites',
    profile: 'Profile',
  },
};
